version: '3'

services:
  php:
    build:
      context: ./php
    expose:
      - 9000
    volumes:
      - ../app:/app
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=php"

  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    volumes:
      - ../app:/app
      - ../app/web/tmp_uploads:/tmp_uploads
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_MY_DATABASE: db
      TZ: "Europe/Moscow"
    volumes:
      - ./volumes/mysql/db/:/var/lib/mysql/
    ports:
      - "3306:3306"